### ISSUE TITLE
Does this already work?

### ISSUE THREAD

**Issue by syryl** [Sachin-A/recaptcha-breaker#1]
Because i have problem:

`
Traceback (most recent call last):
  File "recaptchaBot.py", line 102, in <module>
    driver = webdriver.Firefox(executable_path = projectRoot + "/geckodriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1
`

**Comment by Sachin-A** [comment]
Without much else to go on, I suggest you try upgrading your install of firefox since it typically happens when the geckodriver's capabilities don't match the browser's.  
You can check the [selenium logs](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG) to see which driver version works
